### PR TITLE
Support Ruby 3.0 or later

### PR DESCRIPTION
**Pull request by ashie**
Signed-off-by: Takuro Ashie <ashie@clear-code.com>

### CODE REVIEW

**Comment by ashie** [comment]
Failed to load aws-sdk-core.
```
Using fluent-plugin-s3 1.6.1 from source at `.`
Bundle complete! 5 Gemfile dependencies, 28 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
/opt/hostedtoolcache/Ruby/3.1.0/x64/bin/ruby -w -I"lib:lib:test" /opt/hostedtoolcache/Ruby/3.1.0/x64/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/rake_test_loader.rb "test/test_in_s3.rb" "test/test_out_s3.rb" 
/opt/hostedtoolcache/Ruby/3.1.0/x64/lib/ruby/gems/3.1.0/gems/aws-sdk-core-3.125.5/lib/aws-sdk-core/xml/parser.rb:74:in `set_default_engine': Unable to find a compatible xml library. Ensure that you have installed or added to your Gemfile one of ox, oga, libxml, nokogiri or rexml (RuntimeError)
```

It's caused by https://github.com/aws/aws-sdk-ruby/commit/cc06703d894dd8fa48934d3edc34eb3fbc8c60bf#diff-a9af0bc706c822e7c90ca01122dfac7e0a877a69346c5ae5f805839363aa3d18

It will be removed in the next release: https://github.com/aws/aws-sdk-ruby/commit/64e9ea97c318cb7a10fdf7c0979307a772f06b51#diff-a9af0bc706c822e7c90ca01122dfac7e0a877a69346c5ae5f805839363aa3d18

**Comment by ashie** [comment]
> It's caused by [aws/aws-sdk-ruby@cc06703#diff-a9af0bc706c822e7c90ca01122dfac7e0a877a69346c5ae5f805839363aa3d18](https://github.com/aws/aws-sdk-ruby/commit/cc06703d894dd8fa48934d3edc34eb3fbc8c60bf#diff-a9af0bc706c822e7c90ca01122dfac7e0a877a69346c5ae5f805839363aa3d18)
> 
> It will be removed in the next release: [aws/aws-sdk-ruby@64e9ea9#diff-a9af0bc706c822e7c90ca01122dfac7e0a877a69346c5ae5f805839363aa3d18](https://github.com/aws/aws-sdk-ruby/commit/64e9ea97c318cb7a10fdf7c0979307a772f06b51#diff-a9af0bc706c822e7c90ca01122dfac7e0a877a69346c5ae5f805839363aa3d18)

Sorry, it's wrong.

The correct cause is that rexml isn't default gem anymore as of 3.0, it's a "bundled gem":
https://www.ruby-lang.org/en/news/2020/09/25/ruby-3-0-0-preview1-released/
So that we need to add it to Gemfile or gemspec explicitly.

**Comment by ashie** [comment]
And out_s3 had incompatible issue against Ruby 3.0 or later... 0c63d26a7be96c7fbde384a44474f46d2c4a7b69

**Review by cosmo0920 — APPROVED** [review]
Seems reasonable. Thanks!

**Pull request merged**
