### PR TITLE
Support transfer acceleration for S3 uploads.

### PR DESCRIPTION
**Pull request by baconmania**

### CODE REVIEW

**Comment by repeatedly** [comment]
Could you add this parameter to README?

**Comment by baconmania** [comment]
Done.

**Comment by repeatedly** [comment]
Thx!

**Comment by baconmania** [comment]
Thanks for merging! Do you have a sense for when this will be published?

**Comment by repeatedly** [comment]
New version has beed released several hours ago: https://github.com/fluent/fluent-plugin-s3/commit/e72e826307e42861ef65062aeff805c3c3a445b2

**Comment by baconmania** [comment]
Ah sweet, cheers.

**Pull request merged**
