### PR TITLE
Supports acl options

### PR DESCRIPTION
**Pull request by Hatayaman**
I add acl options to set permission for the object on S3.
It is useful for cross-account access using IAM roles.

### CODE REVIEW

**Comment by poison** [comment]
+1 would be very handy!

**Comment by ijin** [comment]
Ok, so I've looked into this a bit.

At first I thought you can do this with user and bucket policies, but apparently when using cross-account access, the object owner (account B) needs to set an ACL on the object when the bucket owner (account A) is a different account **and** the bucket owner (account A) or whoever else needs to access them.

ref: http://docs.aws.amazon.com/AmazonS3/latest/dev/example-walkthroughs-managing-access-example3.html

I tested this with IAM roles between 2 accounts, and it seems to work as intended. :+1:

**Comment by cejast** [comment]
is this going to be merged soon? we're currently interested in this

**Comment by repeatedly** [comment]
Need to rebase commits.

**Comment by jensraaby** [comment]
It looks like Hatayaman might not be active on Github (this is the only thing they have committed) - if someone else makes a separate Pull Request it will probably get done faster @repeatedly

**Comment by jensraaby** [comment]
PR #91 is a rebase onto master with conflicts resolved

**Comment by repeatedly** [comment]
New PR based on this PR is merged.

**Pull request closed without merging**
