### PR TITLE
ENHANCEMENT: add the additional checksum as a supported put parameter

### PR DESCRIPTION
**Pull request by joe-pll**
Hi, I'm proposing this Pull Request because S3 supports additional checksum options for creating the hash at the upload.
I tested it on my side and it works. What do you think?

Thanks a lot in advance.

### CODE REVIEW

**Comment by ashie** [comment]
Thanks for you contribution!
Could you resolve a failed check?: https://github.com/fluent/fluent-plugin-s3/pull/430/checks?check_run_id=16515271824

**Comment by joe-pll** [comment]
Hi @ashie I modified the commit as requested. Can you please re-run the pipeline?

**Comment by joe-pll** [comment]
Hi @ashie, do you have any update on this?

**Comment by daipom** [comment]
Sorry for the late response.
I will see this.

**Review by ashie — APPROVED** [review]
LGTM

**Comment by ashie** [comment]
Sorry I overlooked it.

**Pull request merged**
