### PR TITLE
Add sse customer key options

### PR DESCRIPTION
**Pull request by yudppp**
Add `Aws::S3::Object#put` options

- sse_customer_algorithm
- sse_customer_key
- sse_customer_key_md5

http://docs.aws.amazon.com/sdkforruby/api/Aws/S3/Object.html#put-instance_method

### CODE REVIEW

**Comment by repeatedly** [comment]
Thx!

**Comment by yudppp** [comment]
🙇

**Comment by repeatedly** [comment]
Released v0.6.8 including this patch.

**Comment by yudppp** [comment]
Thanks to quick response.

**Pull request merged**
