### PR TITLE
s3_object_key_format support %{tag}

### PR DESCRIPTION
**Pull request by breath-co2**
for #179

### CODE REVIEW

**Comment by tpetr** [comment]
I'd love to start using this this -- is there any ETA for this PR getting merged?

**Comment by breath-co2** [comment]
@tpetr It is useful for archive by tag when you have very many tags. otherwise, you need add config for every tag, it's very very cumbersome.
Such as my company tags in s3, it can archive as `account`,  `active`,  `addhp`, `card` ... categorized in each folder.

Conf:
```
<match mysite.logs.*>
    @type s3
    store_as gzip
    remove_tag_prefix mysite.logs.
    s3_object_key_format "%{path}%{tag}/%{time_slice}%{index}.%{file_extension}"
   #... other s3 config
</match>
```

My company example tags:
```
mysite.logs.account
mysite.logs.active
mysite.logs.addhp
mysite.logs.card
mysite.logs.change
mysite.logs.changeflag
mysite.logs.charge
mysite.logs.chat
mysite.logs.checkpoint
mysite.logs.client
mysite.logs.complete
mysite.logs.compose
mysite.logs.consume
mysite.logs.create
mysite.logs.deletechar
mysite.logs.dojo
mysite.logs.ee
mysite.logs.enchant
mysite.logs.equip
mysite.logs.equipup
mysite.logs.event
mysite.logs.evente
mysite.logs.eventevent
mysite.logs.guildpray
mysite.logs.im
mysite.logs.income
mysite.logs.it
mysite.logs.item
mysite.logs.itemoper
mysite.logs.itet
mysite.logs.jumpzone
mysite.logs.kill
mysite.logs.level
mysite.logs.login
mysite.logs.mail
mysite.logs.manual
mysite.logs.nt
mysite.logs.online
mysite.logs.props
mysite.logs.quest
mysite.logs.reward
mysite.logs.social
mysite.logs.team
mysite.logs.test
mysite.logs.tower
mysite.logs.trade
mysite.logs.useskill
```

**Comment by cosmo0920** [comment]
Hi, any chance to write test this feature like as https://github.com/fluent/fluent-plugin-s3/blob/88e6a01d9d1e8cae5ba4b30bb030582dc902684e/test/test_out_s3.rb#L339?
Thanks.

**Comment by repeatedly** [comment]
With v0.14, you can use `${tag[0]}` like syntax to refer tag part in `s3_object_key_format`.
It isn't enough?

**Comment by breath-co2** [comment]
@repeatedly I'm not sure just before, so I'm test it, it isn't working (fluentd: 0.14.9, fluent-plugin-s3: 0.8.0). It's my test config:
```
<source>
    @type dummy
    tag test.mytest1
    dummy {"hello":"world1"}
    auto_increment_key id1
</source>
<source>
    @type dummy
    tag test.mytest2
    dummy {"hello":"world2"}
    auto_increment_key id2
</source>

<match test.*>
    @type copy
    <store>
        @type stdout
    </store>
    <store>
        @type s3
        aws_key_id *****
        aws_sec_key ******
        s3_bucket logs

        format json
        include_tag_key false
        include_time_key false

        path test/

        store_as json
        s3_object_key_format "%{path}${tag[1]}_%{time_slice}_%{index}.%{file_extension}"
        time_slice_wait 10s

        buffer_type file
        buffer_path buffer test.*.buffer
        flush_at_shutdown true
    </store>
</match>
``` 

stdout:
```
2017-02-28 10:02:39.033657000 +0800 test.mytest2: {"hello":"world2","id2":0}
2017-02-28 10:02:39.034384000 +0800 test.mytest1: {"hello":"world1","id1":0}
2017-02-28 10:02:40.072363000 +0800 test.mytest1: {"hello":"world1","id1":1}
2017-02-28 10:02:40.072260000 +0800 test.mytest2: {"hello":"world2","id2":1}
2017-02-28 10:02:41.006109000 +0800 test.mytest1: {"hello":"world1","id1":2}
2017-02-28 10:02:41.006655000 +0800 test.mytest2: {"hello":"world2","id2":2}
^C2017-02-28 10:02:41 +0800 [info]: Received graceful stop
2017-02-28 10:02:42.039991000 +0800 test.mytest2: {"hello":"world2","id2":3}
2017-02-28 10:02:42.042746000 +0800 test.mytest1: {"hello":"world1","id1":3}
```

In s3 file name is that `${tag[1]}_20170228_0.json`. I think ` s3_object_key_format "%{path}${tag[1]}%{time_slice}_%{index}.%{file_extension}"` is not work. 

If use this patch and config like that: 
```
        remove_tag_prefix test.
        s3_object_key_format "%{path}%{tag}/%{time_slice}_%{index}.%{file_extension}"
```
It save 2 files: `test1/20170228_0.json` and `test2/20170228_0.json` by tag.

**Comment by repeatedly** [comment]
@breath-co2 You need to use fluent-plugin-s3 v1.0.0.rc versions. v0.8.x uses old v0.12 API which doesn't support this placeholder feature.

**Comment by breath-co2** [comment]
@repeatedly I'm test in `fluent-plugin-s3 v1.0.0.rc`, but have something warn:
```
2017-02-28 10:43:57 +0800 [warn]: failed to flush the buffer. retry_time=0 next_retry_seconds=2017-02-28 10:43:58 +0800 chunk="5498e2ab25fa96b8a864f706b970ba86" error_class=TypeError error="can't convert nil into an exact number"
  2017-02-28 10:43:57 +0800 [warn]: /fluent-test/plugin-aws-test/out_s33.rb:186:in `at'
  2017-02-28 10:43:57 +0800 [warn]: /fluent-test/plugin-aws-test/out_s33.rb:186:in `write'
  2017-02-28 10:43:57 +0800 [warn]: /usr/local/lib/ruby/gems/2.2.0/gems/fluentd-0.14.10/lib/fluent/plugin/output.rb:1002:in `try_flush'
  2017-02-28 10:43:57 +0800 [warn]: /usr/local/lib/ruby/gems/2.2.0/gems/fluentd-0.14.10/lib/fluent/plugin/output.rb:1217:in `flush_thread_run'
  2017-02-28 10:43:57 +0800 [warn]: /usr/local/lib/ruby/gems/2.2.0/gems/fluentd-0.14.10/lib/fluent/plugin/output.rb:396:in `block (2 levels) in start'
  2017-02-28 10:43:57 +0800 [warn]: /usr/local/lib/ruby/gems/2.2.0/gems/fluentd-0.14.10/lib/fluent/plugin_helper/thread.rb:66:in `block in thread_create
```

I update fluentd to version 0.14.10 but error is still exist, line 186 is that:
```
time_slice = Time.at(chunk.metadata.timekey).utc.strftime(time_slice_format)
```

`log.info chunk.metadata` is that:

```
#<struct Fluent::Plugin::Buffer::Metadata timekey=nil, tag=nil, variables=nil>
```

**Comment by repeatedly** [comment]
@breath-co2 Configuration is above?

**Comment by breath-co2** [comment]
@repeatedly yes

**Comment by repeatedly** [comment]
@breath-co2 Do you reuse v0.8.0's buffer files?

**Comment by breath-co2** [comment]
@repeatedly no. Just now I read the code of fluent-plugin-s3 v1.0.0.rc, I found the changed for this  placeholder feature is use my code, you can see this pull is at 30 Dec 2016, so it is same feature. I am very happy to see that placeholder feature can use in 1.0.0rc. And another wish, plugin of `out_file` can support this feature.

**Comment by repeatedly** [comment]
> And another wish, plugin of out_file can support this feature.

`out_file` has already supported v0.14's this placeholder feature.
Here is configuration example: https://gist.github.com/repeatedly/1c18ea2088d91605018b66f47b1748af

**Comment by breath-co2** [comment]
@repeatedly filter will loss performance. I don't like it, I hope it support the feature by it self. In my project, I changed out_file plugin for 0.12.x, configuration like that: 

```
  <match test.*>
    @type my_file
    path "/data/logs/*.log"
    time_slice_format %Y/%m-%d/${tag}
    remove_tag_prefix test.
    format json
    append true
    include_time_key false
  </match>
```

**Comment by repeatedly** [comment]
In your tag case, following conf is enough.

- conf

```
<match test.*>
  @type file
  path log/test/*${tag[1]}.log
  time_slice_format %Y/%m-%d/
  format json
  append true
  include_time_key false
  <buffer time,tag>
    flush_at_shutdown true
  </buffer>
</match>
```

- command:

```
% echo '{"message":"hello"}' | ~/dev/fluentd/fluentd/bin/fluent-cat test.foo                                            % cat log/test/2017/02-28/foo.log
{"message":"hello"}
```

**Comment by breath-co2** [comment]
@repeatedly it's cool. I did not know before, fluentd updated very quickly, I think you can close this pull.

However, I found one bug in `out_file` plugin. if `path logs/*/${tag[1]}.log`, log will saved `logs/20170228/mytest1.log`, `logs/20170228/mytest2.log`, bug fluentd will create a strange empty folder `logs/*/${tag[1]}.log`

**Comment by repeatedly** [comment]
> `logs/*/${tag[1]}.log`

This is for buffer folder. `out_file` uses `path` setting for `buffer_path` if `buffer_path` is not set.
You can avoid this folder by using following configuration:

```
<match test.*>
  @type file
  path log/test/*${tag[1]}.log
  time_slice_format %Y/%m-%d/
  format json
  append true
  include_time_key false
  <buffer time,tag>
    flush_at_shutdown true
    path /tmp/fluentd_out_file_buf
  </buffer>
</match>
```

**Comment by repeatedly** [comment]
`${tag}` and `s3_object_key_format` issue is fixed by https://github.com/fluent/fluent-plugin-s3/pull/186 and released v1.0.0.rc3.

**Pull request closed without merging**
