### PR TITLE
Add event bridge mode

### PR DESCRIPTION
**Pull request by funtusov**
This PR adds the SQS event bridge mode

### CODE REVIEW

**Comment by rezonick** [comment]
Hi, 
I'll describe a little bit more regarding the PR.
There few ways to notify a newly created object in the S3 bucket to SQS:
1. S3 notifications: the legacy and already support by 'fluent-plugin-s3' way.
2. EventBridge rule: the format of the event is a little bit different.

References:
- https://www.amazonaws.cn/en/new/2021/amazon-s3-event-notifications-amazon-eventbridge-advanced-serverless-applications-faster/

**Comment by ori-rezonate** [comment]
We would love this to be merged :-)
Thanks!

**Comment by ozzycore** [comment]
This is a very useful integration :) Is there any estimate for when this might be merged?

**Review by ashie — CHANGES_REQUESTED** [review]
Sorry for my late response.

The code itself seems OK, could you add document about it to the following page?:
https://github.com/fluent/fluent-plugin-s3/blob/master/docs/input.md

**Comment by rezonick** [comment]
Hi, I opened a PR to `funtusov:event_bridge_mode`, updated the `docs/input.md` as requested :)

**Comment by rezonick** [comment]
Sure :) that's the branch (`rezonick:fix-dco-signoff`)
- https://github.com/funtusov/fluent-plugin-s3/pull/2

Thank you!

**Comment by rezonick** [comment]
Hi,
I followed the instruction on fixing the DCO issue, will you be able to force push it or I did something wrong?

Thanks :)

Screen Shot 2022-10-18 at 10 07 58

**Review by ashie — APPROVED** [review]

**Comment by ashie** [comment]
Thanks!

**Pull request merged**
