### PR TITLE
Add the actual Object metadata when add_object_metadata is enabled

### PR DESCRIPTION
**Pull request by hlx98007**
Fix issue #290

### CODE REVIEW

**Comment by ganmacs** [comment]
Could you check CI?

**Comment by hlx98007** [comment]
@ganmacs Could you guide me on how to resolve this one? I am not too familiar with Ruby and how the CI was setup.

Since the CI test is mocking the data responses and there is no object metadata put initially in the test, I am not sure how to work on the CI part.

**Comment by repeatedly** [comment]
BTW, need new parameter because changing generated record may break existing users.

**Comment by hlx98007** [comment]
@repeatedly If that's the case, I will close the PR because I think this need further discussion.

**Comment by sppwf** [comment]
Hi Guys,

Is there any work done over here?

Thanks
Sergiu Plotnicu

**Pull request closed without merging**
