### PR TITLE
added tagging support for lifecycle

### PR DESCRIPTION
**Pull request by islue**
https://aws.amazon.com/blogs/storage/simplify-your-data-lifecycle-by-using-object-tags-with-amazon-s3-lifecycle/

### CODE REVIEW

**Comment by ashie** [comment]
The patch itself seems O.K.

Could you resolve the failed check?: https://github.com/fluent/fluent-plugin-s3/pull/397/checks?check_run_id=6186618920
 (Please add `signed-off:` field to your commit)

**Comment by islue** [comment]
@ashie DCO check passed, waiting for approval.

**Comment by islue** [comment]
ping

**Comment by ashie** [comment]
Thanks!

**Pull request merged**
